
## Classical statistical inference

- Likelihood
- Regulation? Perhaps


## Machine Learning inference

- Which method should I use random forest or something more advanced?
- Neural networks as universal approximator
- What are Foundational models? LLM is a foundational model, because was trained in a bunch of data, so can be applied across wide range of use cases.


## Convolution Neural Network


input 
kernel
convolutional neuron


$$
y = \sigma \left( \sum \text{input} \otimes \text{kernel} + b \right)
$$



## Geometric Deep Learning




Symmetries and network structure


## Numerical Simulations
- Simulations:
    - n_species = 2
        - No noise and No external force
        - Noise on species 0 and No external force
        - Noise on species 1 and No external force
        - Noise on species 0 and 1, and No external force
        - No noise and External force on species 0
        - No noise and External force on species 1
        - No noise and External force on species 0 and 1
        - Noise on species 0 and External force on species 0
        - Noise on species 1 and External force on species 0
        - Noise on species 0 and 1, and External force on species 0
        - Noise on species 0 and External force on species 1
        - Noise on species 1 and External force on species 1
        - Noise on species 0 and 1, and External force on species 1
        - Noise on species 0 and External force on species 0 and 1
        - Noise on species 1 and External force on species 0 and 1
        - Noise on species 0 and 1, and External force on species 0 and 1

```{mermaid}

```


