project:
  type: book

book:
  title: "Synopsis"
  author: "Carlos Olivares"
  date: "12/18/2025"
  chapters:
    - index.qmd
    # - summary.qmd
    - intro.qmd
    - context.qmd
    - methods.qmd
    - results.qmd
    # - discussion.qmd
    - references.qmd
  appendices: 
    - appendices/GIT.qmd
    - appendices/ProbabilityDistributions.qmd

bibliography: ../Bibliography/GLV_references.bib
csl: physical-review-letters.csl
# filters:
#   - add-file-links.lua
link-citations: true
citeproc: true

format:
  html:
    theme:
      - cosmo
      - brand
    execute:
      echo: false
      warning: false
  pdf:
    documentclass: scrreprt
    execute:
      echo: false
      warning: false



