name: CI Pipelineo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The job is now running on a ${{ runner.os }} event."
      - run: echo "The name of your branch is ${{ github.ref }} and you repository is ${{ github.repository }}."

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install PyTorch (CPU only)
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.7.1

      - name: Install dependencies
        run: |
          pip install pytest
          pip install -e .

      - name: Run test with pytest
        run: |
          pytest

